/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_db;

import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Supawadee Tamo
 */
public class Product_Form extends javax.swing.JFrame {
   private static Product_Form pdf_insert = new Product_Form();
   private static Product_Form pdf_update = new Product_Form();
   private static boolean updateFlag = false;
   private static String setname;
    
    private String sql;

    /**
     * Creates new form Product_Form
     */
    public Product_Form() {
        initComponents();
    }
    
    
    public void setUpdateForm(String name, String decripstion, String productCapCost , String productMin){
       pdf_update.addData.setText("แก้ไขข้อมูลสินค้า");
       pdf_update.productNameTxt.setText(name);
       System.out.print(name);
       pdf_update.DecriptionTxt.setText(decripstion);
       pdf_update.productSellPriceTxt.setText(productCapCost);
       pdf_update.productMinTxt.setText(productMin);
       pdf_update.setVisible(true);
       
       pdf_update.setname = name;
    }
   
    
    public void setUpddateFlag(boolean value){
        pdf_update.updateFlag = value;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addData = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        productNameLb = new javax.swing.JLabel();
        productNameTxt = new javax.swing.JTextField();
        decriptionLb = new javax.swing.JLabel();
        DecriptionTxt = new javax.swing.JTextField();
        procuctMinLb = new javax.swing.JLabel();
        productSellPriceTxt = new javax.swing.JTextField();
        productCapCostLb = new javax.swing.JLabel();
        productMinTxt = new javax.swing.JTextField();
        commit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(228, 241, 254));

        addData.setFont(new java.awt.Font("TH SarabunPSK", 1, 36)); // NOI18N
        addData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addData.setText("เพิ่มข้อมูลสินค้า");

        jPanel1.setBackground(new java.awt.Color(228, 241, 254));

        productNameLb.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        productNameLb.setText("*ชื่อสินค้า");

        productNameTxt.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N

        decriptionLb.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        decriptionLb.setText("*รายละเอียด");

        DecriptionTxt.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        DecriptionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecriptionTxtActionPerformed(evt);
            }
        });

        procuctMinLb.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        procuctMinLb.setText("จำนวนต่ำสุด");

        productSellPriceTxt.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        productSellPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSellPriceTxtActionPerformed(evt);
            }
        });

        productCapCostLb.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        productCapCostLb.setText("ราคาขายต่อชิ้น");

        productMinTxt.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productNameTxt)
                    .addComponent(DecriptionTxt)
                    .addComponent(productNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decriptionLb)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productSellPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(procuctMinLb, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(productMinTxt)
                            .addComponent(productCapCostLb, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(productNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(decriptionLb, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DecriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(procuctMinLb)
                    .addComponent(productCapCostLb))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productSellPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productMinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        commit.setBackground(new java.awt.Color(236, 240, 241));
        commit.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        commit.setText("บันทึก");
        commit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(commit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DecriptionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecriptionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DecriptionTxtActionPerformed

    private void productSellPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSellPriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productSellPriceTxtActionPerformed

    private void commitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitActionPerformed
       Product_Table pt = new Product_Table();
       if(updateFlag){
           editData();
           pt.callEnableButtonCheck();
       }
       else{
           insertData();
           pt.callEnableButtonCheck();
       }

    }//GEN-LAST:event_commitActionPerformed

    private void ShowDataAgain(){
        Product_Table  pt = new Product_Table ();
        pt.ShowData();
    }
    
    private void clearRow(){
        Product_Table  pt = new Product_Table ();
        pt.callClearRow();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_Form().setVisible(true);
            }
        });
    }
   
      
   
            
            
    public void insertData(){
    if(checkDataInForm()){
       String PROD_NAME = productNameTxt.getText();
       double PROD_SALE_PRICE = 0.00;
       String PROD_CAPITAL_COST = productSellPriceTxt.getText();
       String PROD_DESCRIPT = DecriptionTxt.getText();
       int PROD_AMOUNT = 0;
       String PROD_MIN = productMinTxt.getText();
       int PROD_MANU = 0;
       
      String sql = "insert into product(PROD_NAME, PROD_SALE_PRICE, PROD_CAPITAL_COST, PROD_DESCRIPT, PROD_AMOUNT, PROD_MIN, PROD_MANU)\n" +
            "values('"+PROD_NAME+"', "+PROD_SALE_PRICE+", "+PROD_CAPITAL_COST+","+ "'"+PROD_DESCRIPT+"',"+PROD_AMOUNT+", "+PROD_MIN+", "+PROD_MANU+")";
     
        try{
           Connection conn = Gui_db.getConnection();
             Statement stmt  = conn.createStatement();
             stmt.executeUpdate(sql);
             clearTextBox();
             clearRow();
             ShowDataAgain();
             JOptionPane.showMessageDialog(this, "เพิ่มข้อมูลเรียบร้อย");
        
       }
       catch(SQLException ex) {
            System.out.println(ex.getMessage());
          }
       }  
        System.out.println(productNameTxt.getText() +" "+ DecriptionTxt.getText());
    }
    
    
    public void editData(){
       if(checkDataInForm()){
       String PROD_NAME = pdf_update.productNameTxt.getText();
       String PROD_DESCRIPT = pdf_update.DecriptionTxt.getText();
       String PROD_SALE_PRICE = pdf_update.productSellPriceTxt.getText();
       String PROD_MIN = productMinTxt.getText();
     
       
       String sql = "update product "+
               "set PROD_NAME = '"+ PROD_NAME + 
               "', PROD_DESCRIPT = '" +PROD_DESCRIPT+ 
               "', PROD_SALE_PRICE = "+ PROD_SALE_PRICE +
               ",PROD_MIN = " + PROD_MIN +
               " WHERE PROD_NAME = '" + pdf_update.setname+ "'";
        System.out.print(sql);       
        try{
            Connection conn = Gui_db.getConnection();
            Statement stmt = conn.createStatement();
            stmt.executeUpdate(sql);            
        } catch(SQLException ex){
            System.out.println(ex.getMessage());
        }       
        
        Product_Table PT  = new Product_Table();    
        PT.callClearRow();
        PT.ShowData();
        JOptionPane.showMessageDialog(null, "แก้ไขข้อมูลเรียบร้อยแล้ว");
        pdf_update.dispose();
       }  
    }
    
    public void clearTextBox(){
        productNameTxt.setText("");
        productSellPriceTxt.setText("");
        DecriptionTxt.setText("");
        productMinTxt.setText("");
    }
              
    public void openFrame(){
      pdf_insert.setVisible(true);
    }
    
    public boolean checkDataInForm() {
        if (!isNumeric(productSellPriceTxt.getText()) && !isNumeric(productMinTxt.getText())) {
            String message = "กรุณากรอกข้อมูลราคาขายต่อชิ้นและจำนวนต่ำสุด";
            JOptionPane.showMessageDialog(null, message);
            return false;
        }
        else if(!isNumeric(productSellPriceTxt.getText())){
            String message = "กรุณากรอกข้อมูลราคาขายต่อชิ้น";
            JOptionPane.showMessageDialog(null, message);
            return false;
        }
        else if(!isNumeric(productMinTxt.getText())){
            String message = "กรุณากรอกข้อมูลต่ำสุด";
            JOptionPane.showMessageDialog(null, message);
            return false;
        }               
        return true;
    }
    
     public static boolean isNumeric(String str) {
        return str.matches("-?\\d+(\\.\\d+)?");  //match a number with optional '-' and decimal.
    }
     
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DecriptionTxt;
    private javax.swing.JLabel addData;
    private javax.swing.JButton commit;
    private javax.swing.JLabel decriptionLb;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel procuctMinLb;
    private javax.swing.JLabel productCapCostLb;
    private javax.swing.JTextField productMinTxt;
    private javax.swing.JLabel productNameLb;
    private javax.swing.JTextField productNameTxt;
    private javax.swing.JTextField productSellPriceTxt;
    // End of variables declaration//GEN-END:variables
}
