/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_db;

import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author KAZDO
 */
public class OrderMaterialForm extends javax.swing.JFrame {

    private static OrderMaterialForm INSERT_FRAME = new OrderMaterialForm();
    private static OrderMaterialForm UPDATE_FRAME = new OrderMaterialForm();
    private static boolean updateFlag = false;
    private static String mor_id = "";
    DefaultComboBoxModel cbModel = new DefaultComboBoxModel();

    /**
     * Creates new form OrderProductForm
     */
    public OrderMaterialForm() {
        initComponents();

    }

    public void setUpdateForm(String id, Date date, String empName) {
        mor_id = id;
        System.out.println(empName);
        JTextFieldDateEditor editor1 = (JTextFieldDateEditor) INSERT_FRAME.recDate.getDateEditor();
        editor1.setEditable(false);
        UPDATE_FRAME.getMat_NameToCBBupdate();
        UPDATE_FRAME.titleLabel.setText("แก้ไขข้อมูลออเดอร์วัสดุ");
        UPDATE_FRAME.empNameCBB.setSelectedItem(empName);
        UPDATE_FRAME.recDate.setDate(date);
        UPDATE_FRAME.setVisible(true);
    }

    public void setUpdateFlag(boolean value) {
        UPDATE_FRAME.updateFlag = value;
    }

    public void openInsertFrame() {

        JTextFieldDateEditor editor1 = (JTextFieldDateEditor) INSERT_FRAME.recDate.getDateEditor();
        editor1.setEditable(false);
        INSERT_FRAME.clearTextBox();
        INSERT_FRAME.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        empNameCBB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        recDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));

        jPanel1.setBackground(new java.awt.Color(246, 36, 89));

        empNameCBB.setBackground(new java.awt.Color(200, 247, 197));
        empNameCBB.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        empNameCBB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel2.setText("* ชื่อพนักงาน");

        recDate.setMaxSelectableDate(new java.util.Date(253370743311000L));

        recDate.setMinSelectableDate(new java.util.Date(-62135791089000L));
        Date date1 = new Date();
        Calendar c1 = Calendar.getInstance();
        c1.setTime(date1);
        c1.set(Calendar.YEAR, 2017);
        recDate.setDate(c1.getTime());
        recDate.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N

        jLabel6.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel6.setText("* วันที่สั่งวัสดุ");

        submitBtn.setBackground(new java.awt.Color(236, 240, 241));
        submitBtn.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        submitBtn.setText("บันทึก");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        titleLabel.setBackground(new java.awt.Color(44, 62, 80));
        titleLabel.setFont(new java.awt.Font("TH SarabunPSK", 1, 36)); // NOI18N
        titleLabel.setText("เพิ่มข้อมูลออเดอร์วัสดุ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(empNameCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recDate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(titleLabel)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(empNameCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(recDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        OrderMaterialTable OMT = new OrderMaterialTable();
        if (updateFlag) {
            editData();
            OMT.callEnableButtonCheck();
        } else {
            insertData();
            OMT.callEnableButtonCheck();
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    public void insertData() {

        Date date1 = recDate.getDate();
        DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
        String orderDateTxt = df1.format(date1);

        String empNAME = empNameCBB.getSelectedItem().toString();
        String[] sp = empNAME.split(" ");
                
        System.out.println("sp[1] = " + sp[0]);
        System.out.println("sp[2] = " + sp[2]);
        String sql = "INSERT INTO MATERIAL_ORDER(MOR_COST, MOR_DATE, EMP_ID )"
                + "VALUES(0.0, '" + orderDateTxt + "', (select EMP_ID from EMPLOYEE where EMP_FNAME = '" + sp[0] + "' and EMP_LNAME = '" + sp[2]  + "'));";
        System.out.println(sql);
        try {
            Connection conn = Gui_db.getConnection();
            Statement stmt = conn.createStatement();
            stmt.executeUpdate(sql);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        OrderMaterialTable omt = new OrderMaterialTable();
        omt.callClearRow();
        omt.callShowDataRecord();
        JOptionPane.showMessageDialog(null, "เพิ่มข้อมูลเรียบร้อยแล้ว");
        clearTextBox();

    }

    public void editData() {

        Date date1 = recDate.getDate();
        DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
        String orderDateTxt = df1.format(date1);
        String empName = empNameCBB.getSelectedItem().toString();
        String[] sp = empName.split(" ");
        
        String sql = "UPDATE MATERIAL_ORDER " +
                     "SET MOR_COST = 0.00, MOR_DATE = '" + orderDateTxt + "'," +
                     "EMP_ID = (select EMP_ID from EMPLOYEE where EMP_FNAME = '" + sp[0]   + "' and EMP_LNAME = '" +  sp[2]  + "') " + 
                     "WHERE MOR_ID = " +  mor_id   +";";
        System.out.println(sql);
        try {
            Connection conn = Gui_db.getConnection();
            Statement stmt = conn.createStatement();
            stmt.executeUpdate(sql);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        OrderMaterialTable omt = new OrderMaterialTable();
        omt.callClearRow();
        omt.callShowDataRecord();
        JOptionPane.showMessageDialog(null, "เพิ่มข้อมูลเรียบร้อยแล้ว");
        clearTextBox();
        UPDATE_FRAME.dispose();

    }

    public void getMat_NameToCBBinsert() {
        String sql = "select EMP_FNAME, EMP_LNAME from EMPLOYEE;";
        try {
            Connection conn = Gui_db.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            int row = 0;
            while (rs.next()) {

                cbModel.addElement(rs.getString(1) + "  " + rs.getString(2));
                row++;
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        INSERT_FRAME.empNameCBB.setModel(cbModel);

    }
    
      public void getMat_NameToCBBupdate() {
        String sql = "select EMP_FNAME, EMP_LNAME from EMPLOYEE;";
        try {
            Connection conn = Gui_db.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            int row = 0;
            while (rs.next()) {

                cbModel.addElement(rs.getString(1) + "  " + rs.getString(2));
                row++;
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        UPDATE_FRAME.empNameCBB.setModel(cbModel);

    }
    
    
    
    public void clearTextBox() {

    }

    public static boolean isNumeric(String str) {
        return str.matches("-?\\d+(\\.\\d+)?");  //match a number with optional '-' and decimal.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> empNameCBB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser recDate;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
