/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_db;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author user
 */
public class OTForm extends javax.swing.JFrame {
    private static OTForm inserframe = new OTForm();
    private static OTForm updateframe = new OTForm();
    private static boolean updateFlag = false;
    private static String updateID;
    private static String otId;
    DefaultComboBoxModel cbModel = new DefaultComboBoxModel();

    /**
     * Creates new form TimeworkEmpForm
     */
    public void setUpdateForm(String empID,Date date,String empName,Time timein,Time timeout, String otId) {
        updateframe.setSelectedComponent();
        System.out.println(empName);
        JTextFieldDateEditor editor = (JTextFieldDateEditor) updateframe.Fdate.getDateEditor();
        editor.setEditable(false);
        this.otId = otId;
        updateframe.titleLabel.setText("แก้ไขข้อมูลเวลาการทำงานเวลา OT ของพนักงาน");
        updateframe.Fdate.setDate(date);
        updateframe.employeeCbb.setSelectedItem(empName);
        updateframe.timeIn.setValue(timein);
        updateframe.timeOut.setValue(timeout);
        updateframe.
        updateframe.setVisible(true);
    }
    public OTForm() {
        initComponents();
    }
    public void setupdateFlag(boolean value)
    {
        updateframe.updateFlag = value;
    }
     public void openinserFrame() {
        //empF.showDataRecord();
        inserframe.setSelectedComponent();
        JTextFieldDateEditor editor = (JTextFieldDateEditor) inserframe.Fdate.getDateEditor();
        editor.setEditable(false);
        JFormattedTextField tf1 = ((JSpinner.DefaultEditor)inserframe.timeIn.getEditor()).getTextField();
        tf1.setEditable(false);
        JFormattedTextField tf2 = ((JSpinner.DefaultEditor)inserframe.timeOut.getEditor()).getTextField();
        tf2.setEditable(false);
        inserframe.setVisible(true);
       

     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fdate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        timeIn = new javax.swing.JSpinner(sm);
        jLabel4 = new javax.swing.JLabel();
        SpinnerDateModel sm1 =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        timeOut = new javax.swing.JSpinner(sm1);
        jLabel5 = new javax.swing.JLabel();
        employeeCbb = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(162, 222, 208));

        titleLabel.setFont(new java.awt.Font("TH SarabunPSK", 1, 36)); // NOI18N
        titleLabel.setText("เพิ่มข้อมูลเวลาการทำงานเวลา OT ของพนักงาน");

        jLabel2.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel2.setText(" *วันที่เข้าทำงาน\t");

        Fdate.setBackground(new java.awt.Color(236, 240, 241));
        Fdate.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        Fdate.setMaxSelectableDate(new java.util.Date(253370743290000L));
        Calendar c = Calendar.getInstance();
        c.setTime(date);
        c.set(Calendar.YEAR, 2017);
        Fdate.setDate(c.getTime());

        jLabel3.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel3.setText("*เวลาที่เข้าทำงาน");

        JSpinner.DateEditor de = new JSpinner.DateEditor(timeIn, "HH:mm:ss");
        timeIn.setEditor(de);
        timeIn.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N

        jLabel4.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel4.setText("*เวลาที่ออกทำงาน");

        de = new JSpinner.DateEditor(timeOut, "HH:mm:ss");
        timeOut.setEditor(de);
        timeOut.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N

        jLabel5.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel5.setText("*พนักงาน");

        employeeCbb.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        employeeCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submitButton.setBackground(new java.awt.Color(236, 240, 241));
        submitButton.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        submitButton.setText("บันทึก");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Fdate, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(timeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(timeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(employeeCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
         TimeEmpTable TET = new TimeEmpTable();
        if(updateFlag) {
            editData();
           // TET.callEnableButtonCheck();
        }
        else {
            insertData();
           // TET.enableButtonCheck();
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    public void editData() {
        Date time1 = (Date) timeIn.getValue();
        Date time2 = (Date) timeOut.getValue();
        Date date = Fdate.getDate();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat tf = new SimpleDateFormat("HH:mm:ss");
        String FDate = df.format(date); //แปลงคำสั่งจากdate เป็น staing
        String TimeIn = tf.format(time1);
        String TimeOut = tf.format(time2);
        String EmpName = employeeCbb.getSelectedItem().toString();
        String[] splitName = EmpName.split(" ");
        long diff = time2.getTime() - time1.getTime();
        long diffMinutes = diff / (60 * 1000) % 60;
        
        String sql = "UPDATE OVER_TIME " + 
                     "SET OT_DATE = '" + FDate + "', OT_START_TIME = '" +TimeIn+"', OT_QUIT_TIME = '"+TimeOut+
                     "', EMP_ID = (select EMP_ID from employee where " +
                     "EMP_FNAME = '" + splitName[0] + "' and EMP_LNAME = '" + splitName[1]+"')" + 
                     " where OT_ID = " + otId;
        System.out.println(sql);
        
        try {
                Connection conn = Gui_db.getConnection();
                Statement stmt = conn.createStatement();
                stmt.executeUpdate(sql);
            } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
            }
        OTTable ToT = new OTTable();
        ToT.callClearRow();
        ToT.callShowDataRecord();
        JOptionPane.showMessageDialog(null, "แก้ไขข้อมูลเรียบร้อยแล้ว");
        ToT.callEnableButtonCheck();
        
        updateframe.dispose();
        
       
                     
        
    }
    /**
     * @param args the command line arguments
     */
    private void setSelectedComponent() {
        String sql = "select EMP_FNAME, EMP_LNAME from employee";
            try (Connection conn = Gui_db.getConnection();
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(sql)) {

            // loop through the result set
            while (rs.next()) {
                cbModel.addElement(rs.getString(1) + " " + rs.getString(2));
            }
            
            } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
            }
        employeeCbb.setModel(cbModel);
    }
    public void insertData() {
            Date time1 = (Date) timeIn.getValue();
            Date time2 = (Date) timeOut.getValue();
            Date date = Fdate.getDate();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd"); // ต้องมีรูปแบบ
            DateFormat tf = new SimpleDateFormat("HH:mm:ss"); // ต้องมีรูปแบบ
            String FDate = df.format(date); //แปลงคำสั่งจากdate เป็น staing
            String TimeIn = tf.format(time1);
            String TimeOut = tf.format(time2);
            String EmpName = employeeCbb.getSelectedItem().toString();
            String[] splitName = EmpName.split(" ");
            long diff = time2.getTime() - time1.getTime();
            long diffMinutes = diff / (60 * 1000) % 60;
            
            
            String sql = "INSERT INTO OVER_TIME(EMP_ID,OT_DATE,OT_START_TIME,OT_QUIT_TIME,OT_DURATION)\n"+
                          "VALUES((select EMP_ID from employee where " +
                          "EMP_FNAME = '" + splitName[0] + "' and EMP_LNAME = '" + splitName[1] 
                          +"'), '"+ FDate + "'" + ", '"+TimeIn+"' , '"+TimeOut+"' ,"+diffMinutes/60.0+")";
                          
            System.out.println(sql);
                  try {
                    Connection conn = Gui_db.getConnection();
                    Statement stmt = conn.createStatement();
                    stmt.executeUpdate(sql);
                } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                }
            OTTable ToT = new OTTable();
            ToT.callClearRow();
            ToT.callShowDataRecord();
            JOptionPane.showMessageDialog(null, "เพิ่มข้อมูลเรียบร้อยแล้ว");
            
            
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OTForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fdate;
    private javax.swing.JComboBox<String> employeeCbb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitButton;
    private javax.swing.JSpinner timeIn;
    private javax.swing.JSpinner timeOut;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
