/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class TimeEmpTable extends javax.swing.JFrame {
              private static  TimeEmpTable TeT = new TimeEmpTable();
              private DefaultTableModel model = new DefaultTableModel();
              private Object[] data = new Object[0];
              private static String date = "";
              private static String timein = "";
              private static String timeout = "";
              private static String empName = "";
              private static String getEmpDateStart = null;
              private static String getEmpDateFinish = null;
    /**
     * Creates new form TimeEmpTable
     */
    public TimeEmpTable() {
        initComponents();
        model = (DefaultTableModel)timework_table.getModel(); 
        showDataRecord();
    }
    public void enableButtonCheck() {
        String check = getcheckID();
        String[] s = check.split(",");
        if(timework_table.getRowCount() > 0)
            checkAllButton.setEnabled(true);
        else
            checkAllButton.setEnabled(false);
        
        if (check.equals("")) {
            EditButton.setEnabled(false);
            DeleteButton.setEnabled(false);
            checkAllButton.setText("เลือกทั้งหมด");
        }
        
        else if (s.length == 1) {
            EditButton.setEnabled(true);
            DeleteButton.setEnabled(true);
            checkAllButton.setText("ยกเลิกการเลือก");
        }
        
        else {
            DeleteButton.setEnabled(true);
            EditButton.setEnabled(false);
        }
         
        
    }
    public String getcheckID()
   {
       String id="";
       for(int i=0;i<timework_table.getRowCount();i++)
       {
           if(Boolean.valueOf(timework_table.getValueAt(i, 0).toString()))
           {
               id += timework_table.getValueAt(i, 2).toString() +",";
               empName = timework_table.getValueAt(i, 3).toString();
               date = timework_table.getValueAt(i, 4).toString();
               timein = timework_table.getValueAt(i, 5).toString();
               timeout = timework_table.getValueAt(i, 6).toString();
               
               
           }
       }
       if(id.equals(""))
           return "";
       
       return id.substring(0, id.length()-1);
   }
    
    public void clearRow() {
        int row = model.getRowCount()-1;
        while(row > -1) {
            model.removeRow(row);
            row--;
        }
    }
     public void showDataRecord() {
              String sql = "select EMP_ID,EMP_FNAME,EMP_LNAME,TW_DATE,TW_START_TIME,TW_QUIT_TIME"
                      + " from TIME_WORK natural join employee" + " order by  TW_DATE desc";
              
              try (Connection conn = Gui_db.getConnection();
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(sql)) {
                  
              int row=0;
              while (rs.next()) {
                model.addRow(data);
                model.setValueAt(false, row, 0);
                model.setValueAt(row+1, row, 1);
                model.setValueAt(rs.getString(1), row, 2);
                model.setValueAt(rs.getString(2) + " " + rs.getString(3), row, 3);
                model.setValueAt(rs.getString(4), row, 4);
                model.setValueAt(rs.getString(5), row, 5);
                model.setValueAt(rs.getString(6), row, 6);
                
             
                row++;
              }
              }catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                }
             
              
     }
    public void callEnableButtonCheck()
    {
        TeT.enableButtonCheck();
    }
    public void callClearRow() {
        TeT.clearRow();
    }
    
    public void callShowDataRecord() {
        TeT.showDataRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchEmpFNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        searchEmpLNameTxt = new javax.swing.JTextField();
        searchEmpName = new javax.swing.JButton();
        searchSpecialBTN = new javax.swing.JButton();
        ResetEmpName = new javax.swing.JButton();
        checkAllButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        timework_table = new javax.swing.JTable();
        Btn_MainMenu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        InsertButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(135, 211, 124));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(135, 211, 124));

        Btn_back.setBackground(new java.awt.Color(236, 240, 241));
        Btn_back.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        Btn_back.setText("ย้อนกลับ");
        Btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("TH SarabunPSK", 1, 36)); // NOI18N
        jLabel1.setText("ข้อมูลการทำงานเวลาปกติของพนักงาน");

        jPanel2.setBackground(new java.awt.Color(135, 211, 124));

        jLabel2.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel2.setText("ชื่อ");

        searchEmpFNameTxt.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        searchEmpFNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmpFNameTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        jLabel3.setText("นามสกุล");

        searchEmpLNameTxt.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        searchEmpLNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmpLNameTxtActionPerformed(evt);
            }
        });

        searchEmpName.setBackground(new java.awt.Color(236, 240, 241));
        searchEmpName.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        searchEmpName.setText("ค้นหา");
        searchEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmpNameActionPerformed(evt);
            }
        });

        searchSpecialBTN.setBackground(new java.awt.Color(236, 240, 241));
        searchSpecialBTN.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        searchSpecialBTN.setText("ระบุเงื่อนไข");
        searchSpecialBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSpecialBTNActionPerformed(evt);
            }
        });

        ResetEmpName.setBackground(new java.awt.Color(236, 240, 241));
        ResetEmpName.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        ResetEmpName.setText("รีเซ็ต");
        ResetEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetEmpNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchEmpFNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchEmpLNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchSpecialBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ResetEmpName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchEmpFNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchEmpLNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ResetEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchSpecialBTN))))
                .addContainerGap())
        );

        checkAllButton.setBackground(new java.awt.Color(44, 62, 80));
        checkAllButton.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        checkAllButton.setForeground(new java.awt.Color(255, 255, 255));
        checkAllButton.setText("เลือกทั้งหมด");
        checkAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAllButtonActionPerformed(evt);
            }
        });

        timework_table.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        timework_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "เลือก", "ลำดับ", "หมายเลขพนักงาน", "พนักงาน", "วันที่", "เวลาเข้า", "เวลาออก"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        timework_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        timework_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timework_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(timework_table);
        if (timework_table.getColumnModel().getColumnCount() > 0) {
            timework_table.getColumnModel().getColumn(0).setResizable(false);
            timework_table.getColumnModel().getColumn(0).setPreferredWidth(55);
            timework_table.getColumnModel().getColumn(1).setResizable(false);
            timework_table.getColumnModel().getColumn(1).setPreferredWidth(55);
            timework_table.getColumnModel().getColumn(2).setResizable(false);
            timework_table.getColumnModel().getColumn(2).setPreferredWidth(125);
            timework_table.getColumnModel().getColumn(3).setResizable(false);
            timework_table.getColumnModel().getColumn(3).setPreferredWidth(220);
            timework_table.getColumnModel().getColumn(4).setResizable(false);
            timework_table.getColumnModel().getColumn(4).setPreferredWidth(120);
            timework_table.getColumnModel().getColumn(5).setResizable(false);
            timework_table.getColumnModel().getColumn(5).setPreferredWidth(90);
            timework_table.getColumnModel().getColumn(6).setResizable(false);
            timework_table.getColumnModel().getColumn(6).setPreferredWidth(90);
        }

        Btn_MainMenu.setBackground(new java.awt.Color(236, 240, 241));
        Btn_MainMenu.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        Btn_MainMenu.setText("เมนูหลัก");
        Btn_MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MainMenuActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(135, 211, 124));

        InsertButton.setBackground(new java.awt.Color(236, 240, 241));
        InsertButton.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        InsertButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win_10\\Downloads\\add (1).png")); // NOI18N
        InsertButton.setText(" เพิ่ม");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        EditButton.setBackground(new java.awt.Color(236, 240, 241));
        EditButton.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        EditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_db/tools.png"))); // NOI18N
        EditButton.setText("แก้ไข");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(236, 240, 241));
        DeleteButton.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        DeleteButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win_10\\Downloads\\delete (1).png")); // NOI18N
        DeleteButton.setText("ลบ");
        DeleteButton.setActionCommand(" ลบ");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InsertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(InsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(checkAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(checkAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(Btn_MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        TimeworkEmpForm tw = new TimeworkEmpForm();
        
        tw.openinserFrame();
        
        
        
    }//GEN-LAST:event_InsertButtonActionPerformed

   
    public void openFrame() {
        TeT.clearRow();
        TeT.showDataRecord();
        TeT.enableButtonCheck();
        TeT.setVisible(true);
     }
    private void checkAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAllButtonActionPerformed
         if(checkAllButton.getText().equals("เลือกทั้งหมด")) {
            for(int i=0; i<timework_table.getRowCount(); i++)
                model.setValueAt(true, i, 0);
            checkAllButton.setText("ยกเลิกการเลือก");
        } else {
            for(int i=0; i<timework_table.getRowCount(); i++)
                model.setValueAt(false, i, 0);
            checkAllButton.setText("เลือกทั้งหมด");
        }
    }//GEN-LAST:event_checkAllButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        String id = getcheckID();
        TimeworkEmpForm tw = new TimeworkEmpForm();
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat formatter = new SimpleDateFormat("HH:mm:ss");
       // tw.setupdateFlag(true);
        
        try {
            java.sql.Time time1 = new java.sql.Time(formatter.parse(timein).getTime());
            java.sql.Time time2 = new java.sql.Time(formatter.parse(timeout).getTime());
            Date reportDate = format.parse(date);
            tw.setupdateFlag(true);
            tw.setUpdateForm(id,reportDate,empName, time1,time2, getTwId());
        } catch (ParseException ex) {
            Logger.getLogger(TimeEmpTable.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
          
         
    }//GEN-LAST:event_EditButtonActionPerformed

    private void timework_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timework_tableMouseClicked
        enableButtonCheck();
    }//GEN-LAST:event_timework_tableMouseClicked

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        String num[] = getcheckID().split(",");;
        String s[] = new String[3];
        Array(s);
        
        int YesOrNo = JOptionPane.showConfirmDialog(null,"ลบข้อมูลทั้งหมดจำนวน " + num.length + " แถว","คำเตือนในการลบ", JOptionPane.YES_NO_OPTION);
                if(YesOrNo == JOptionPane.YES_NO_OPTION){
                    String sql = "DELETE from time_work "+"WHERE EMP_ID in (" + s[0] +")" +" AND "
                                +"TW_DATE in (" + s[1] +")"+" AND "+"TW_START_TIME in (" + s[2] +")";
                    System.out.println(sql);
                try  {
                Connection conn = Gui_db.getConnection();
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.executeUpdate();
                
                }
               
               catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                        
                }
               TeT.clearRow();
               TeT.showDataRecord();
               enableButtonCheck();
               JOptionPane.showMessageDialog(this, "ลบข้อมูลเรียบร้อยแล้ว "); 
              }
                
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ResetEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetEmpNameActionPerformed
        openFrame();
        searchEmpFNameTxt.setText("");
        searchEmpLNameTxt.setText("");
        getEmpDateStart = null;
        getEmpDateFinish = null;
    }//GEN-LAST:event_ResetEmpNameActionPerformed

    private void searchSpecialBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSpecialBTNActionPerformed
        TimeEmpFromSpecialSearch TEFSS = new TimeEmpFromSpecialSearch();
        TEFSS.openFrame();
    }//GEN-LAST:event_searchSpecialBTNActionPerformed

    private void searchEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmpNameActionPerformed
        showSearchEmpNameTimeWork();
    }//GEN-LAST:event_searchEmpNameActionPerformed

    private void searchEmpLNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmpLNameTxtActionPerformed
        showSearchEmpNameTimeWork();
    }//GEN-LAST:event_searchEmpLNameTxtActionPerformed

    private void searchEmpFNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmpFNameTxtActionPerformed
        showSearchEmpNameTimeWork();
    }//GEN-LAST:event_searchEmpFNameTxtActionPerformed

    private void Btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_backActionPerformed
        new EmpWorkTimeOrOT().setVisible(true);
        TeT.setVisible(false);
    }//GEN-LAST:event_Btn_backActionPerformed

    private void Btn_MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MainMenuActionPerformed
        new MainFrame().setVisible(true);
        TeT.setVisible(false);
    }//GEN-LAST:event_Btn_MainMenuActionPerformed

    
  public void showSearchEmpNameTimeWork(){
     TeT.clearRow();
     TeT.searchEmpNameTimeWork();
     TeT.enableButtonCheck();
     TeT.setVisible(true);




}
    
    
    public void searchEmpNameTimeWork(){
      
        System.out.println(getEmpDateStart + " " + getEmpDateFinish);
        
        if(getEmpDateStart == null && getEmpDateFinish == null){
            String searchEmpFName = searchEmpFNameTxt.getText();
            String searchEmpLName = searchEmpLNameTxt.getText();
        
            String sql = "select EMP_ID,EMP_FNAME,EMP_LNAME,TW_DATE,TW_START_TIME,TW_QUIT_TIME"
                          + " from TIME_WORK natural join employee where EMP_FNAME like'%" +  searchEmpFName  + "%' and EMP_LNAME like'%" + searchEmpLName  + "%' order by  TW_DATE desc";

            try{
                Connection con = Gui_db.getConnection();
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);

                int row = 0;
                while(rs.next()){
                    model.addRow(data);
                    model.setValueAt(false, row, 0);
                    model.setValueAt(row+1, row, 1);
                    model.setValueAt(rs.getString(1), row, 2);
                    model.setValueAt(rs.getString(2) + " " + rs.getString(3), row, 3);
                    model.setValueAt(rs.getString(4), row, 4);
                    model.setValueAt(rs.getString(5), row, 5);
                    model.setValueAt(rs.getString(6), row, 6);


                    row++;

                }



            }catch(SQLException ex){
                System.out.println(ex.getMessage());

            }
        }else{
            
            String searchEmpFName = searchEmpFNameTxt.getText();
            String searchEmpLName = searchEmpLNameTxt.getText();

            String sql = "select EMP_ID,EMP_FNAME,EMP_LNAME,TW_DATE,TW_START_TIME,TW_QUIT_TIME"
                          + " from TIME_WORK natural join employee where EMP_FNAME like'%" +  searchEmpFName  + "%' and EMP_LNAME like'%" + searchEmpLName  + "%' " +  
                          "and TW_DATE >= '" + getEmpDateStart  + "' and TW_DATE <= '" +  getEmpDateFinish  + "' order by  TW_DATE desc";
            System.out.println(sql);
            try{
                Connection con = Gui_db.getConnection();
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);

                int row = 0;
                while(rs.next()){
                    model.addRow(data);
                    model.setValueAt(false, row, 0);
                    model.setValueAt(row+1, row, 1);
                    model.setValueAt(rs.getString(1), row, 2);
                    model.setValueAt(rs.getString(2) + " " + rs.getString(3), row, 3);
                    model.setValueAt(rs.getString(4), row, 4);
                    model.setValueAt(rs.getString(5), row, 5);
                    model.setValueAt(rs.getString(6), row, 6);


                    row++;

                }



            }catch(SQLException ex){
                System.out.println(ex.getMessage());

            }
            
            
            
        }
       
        
        
        
        
        
        
        
    }
    

    public void showDataSpecialSearch(String EmpDateStart, String EmpDateFinish){
        getEmpDateStart = EmpDateStart;
        getEmpDateFinish = EmpDateFinish;
        TeT.clearRow();
        TeT.getDataSpecialSearch(EmpDateStart, EmpDateFinish);
        TeT.enableButtonCheck();
        TeT.setVisible(true);
    }
    
    public void getDataSpecialSearch(String EmpDateStart, String EmpDateFinish){
        
        searchEmpFNameTxt.setText("");
        searchEmpLNameTxt.setText("");       
        String sql = "SELECT EMP_ID,EMP_FNAME,EMP_LNAME,TW_DATE,TW_START_TIME,TW_QUIT_TIME " +
                     "FROM TIME_WORK NATURAL JOIN EMPLOYEE WHERE TW_DATE >= '" +  EmpDateStart + "' and TW_DATE <= '" +  EmpDateFinish +"' order by  TW_DATE desc;";
        System.out.println(sql);
        try{
            Connection con = Gui_db.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            int row = 0;
            while(rs.next()){
                model.addRow(data);
                model.setValueAt(false, row, 0);
                model.setValueAt(row+1, row, 1);
                model.setValueAt(rs.getString(1), row, 2);
                model.setValueAt(rs.getString(2) + " " + rs.getString(3), row, 3);
                model.setValueAt(rs.getString(4), row, 4);
                model.setValueAt(rs.getString(5), row, 5);
                model.setValueAt(rs.getString(6), row, 6);
                
             
                row++;
                
            }
            
            
            
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
            
        }

        
    }
    
    
    
    
    
    public void Array(String[] a) {
        a[0] = "";
        a[1] = "";
        a[2] = "";
        
       for(int i=0;i<timework_table.getRowCount();i++)
       {
           if(Boolean.valueOf(timework_table.getValueAt(i, 0).toString()))
           {
               a[0] += timework_table.getValueAt(i, 2).toString() +",";
               empName = timework_table.getValueAt(i, 3).toString();
                a[1] += "'"+timework_table.getValueAt(i, 4).toString()+"',";
                a[2] += "'"+timework_table.getValueAt(i, 5).toString()+"',";    
           }
       }
        a[0]=a[0].substring(0, a[0].length()-1);
        a[1]=a[1].substring(0, a[1].length()-1);
        a[2]=a[2].substring(0, a[2].length()-1);

                      
    }
    
    public String getTwId() {
        String id= getcheckID();
        String twId = "";
        String getTwId = "select TW_ID from TIME_WORK where TW_DATE = '" + date +"' and "+ "TW_START_TIME = '" + timein + "' and "
                       + "EMP_ID = " + id;
        
        System.out.println(getTwId);    
            try (Connection conn = Gui_db.getConnection();
                    Statement stmt = conn.createStatement();
                    ResultSet rs = stmt.executeQuery(getTwId)) {

                while (rs.next()) {
                    twId = rs.getString(1);
                }

                } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                }
        return twId;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeEmpTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeEmpTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeEmpTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeEmpTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TeT.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_MainMenu;
    private javax.swing.JButton Btn_back;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton InsertButton;
    private javax.swing.JButton ResetEmpName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checkAllButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchEmpFNameTxt;
    private javax.swing.JTextField searchEmpLNameTxt;
    private javax.swing.JButton searchEmpName;
    private javax.swing.JButton searchSpecialBTN;
    private javax.swing.JTable timework_table;
    // End of variables declaration//GEN-END:variables
}
